### ISSUE TITLE
 tplink-smarthome-api --help error

### ISSUE THREAD

**Issue by croziors** [plasticrake/tplink-smarthome-api#32]
/usr/local/lib/node_modules/tplink-smarthome-api/lib/cli.js:51
    console.log(`startDiscovery(${util.inspect(commandParams)})`);
                ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by plasticrake** [comment]
I suspect you're using an unsuppored node version. What's your node version? `node --version`

**Comment by croziors** [comment]
v0.10.30

**Comment by plasticrake** [comment]
As specified in the package.json, you need v4 or greater to use this.

**Comment by croziors** [comment]
node --version
v9.2.1
node ex.js
module.js:544
    throw err;
    ^

Error: Cannot find module 'tplink-smarthome-api'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rig1/ex.js:1:82)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

**Comment by croziors** [comment]
work sorry ;) you can close

**Comment by 850075610** [comment]
> work sorry ;) you can close

How did you solve your problem?
