### ISSUE TITLE
Do LB200 bulbs work?

### ISSUE THREAD

**Issue by mark-hahn** [plasticrake/tplink-smarthome-api#34]
I just bought two LB200 bulbs.  I can't discover them.  Are they too new?

**Comment by plasticrake** [comment]
Do you have other devices that are discovered? They are working in the Kasa app, right?

Can you try this:
Run `npm install -g tplink-smarthome-api` then `tplink-smarthome-api search` and post the output. Also make sure you are running this on the same network as the bulbs.

**Comment by mark-hahn** [comment]
I have two bulbs.  I have been able to find and install them in Kasa.
However finding them is flakey and I have to try a number of times.  Once
installed in Kasa they work fine.

Discovery worked ...

startDiscovery({ discoveryInterval: 2000, discoveryTimeout: 5000 })
LB200(E26) bulb IOT.SMARTBULB 192.168.1.164 9999
8012F4CB205A26730BBDE66014891E4718D2CB1D My Smart Bulb

I could have sworn I tried your discovery before with no luck.

**Comment by mark-hahn** [comment]
More ...

$ tplink-smarthome-api getInfo 192.168.1.164
Sending getInfo command to 192.168.1.164:undefined...
response:
{ sysInfo: { err_code: -2000, err_msg: 'Method not support' },
  cloud:
   { info:
      { username: 'Mark@hahnca.com',
        server: 'devs.tplinkcloud.com',
        binded: 1,
        cld_connection: 1,
        illegalType: 0,
        tcspStatus: 1,
        fwDlPage: '',
        tcspInfo: '',
        stopConnect: 0,
        fwNotifyType: 0,
        err_code: 0 } },
  emeter: { realtime: { power_mw: 11000, err_code: 0 } },
  schedule: { nextAction: { type: -1, err_code: 0 } },
  lighting:
   { lightState:
      { on_off: 1,
        mode: 'normal',
        hue: 0,
        saturation: 0,
        color_temp: 2700,
        brightness: 100,
        err_code: 0 } } }

**Comment by mark-hahn** [comment]
Also ...

$ tplink-smarthome-api details 192.168.1.164
Getting details from 192.168.1.164:undefined...
{ alias: 'My Smart Bulb',
  deviceId: '8012F4CB205A26730BBDE66014891E4718D2CB1D',
  description: 'Smart Wi-Fi LED Bulb with Dimmable Light',
  model: 'LB200(E26)',
  deviceType: 'bulb',
  type: 'IOT.SMARTBULB',
  softwareVersion: '1.7.1 Build 171109 Rel.163935',
  hardwareVersion: '1.0',
  mac: '50C7BFF846CA' }

So this means I can control it now?  I'll try to send a payload via cli as
soon as I figure out what goes in the payload.

**Comment by mark-hahn** [comment]
Send and sendCommand fail

```
$  tplink-smarthome-api send 192.168.1.164 {"system":{"get_sysinfo":{}}}
Sending to 192.168.1.164:undefined...
TCP Timeout
Error: TCP Timeout
    at Timeout._onTimeout (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/lib/client.js:249:20)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)


$ tplink-smarthome-api sendCommand 192.168.1.164 {"system":{"get_sysinfo":{}}}
Sending to 192.168.1.164:undefined...
SyntaxError: Unexpected token s in JSON at position 1
    at JSON.parse (<anonymous>)
    at Bulb._callee2$ (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/lib/device/index.js:230:92)
    at tryCatch (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/core-js/library/modules/_export.js:35:28)
    at /root/.nvm/versions/node/v8.9.3/lib/node_modules/tplink-smarthome-api/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
```

**Comment by mark-hahn** [comment]
It is possible I originally tried the discovery before I configured with Kasa.

**Comment by mark-hahn** [comment]
Apparently things are working.  Thanks and sorry for your trouble.
