### ISSUE TITLE
setLightState not work

### ISSUE THREAD

**Issue by arteck** [plasticrake/tplink-smarthome-api#58]
i have here a bulb LB100 and one problem 
the setLightState does not work for me

```
const plug = client.getDevice({host: ip}).then((device)=> {
            var options = device.sysInfo.light_state;
            Object.entries(options).forEach(([key, value]) => {
                       switch (key) {
                            case 'brightness':
                                Object.assign(options, {[key]: 10});
                           }
                    });
                    device.lighting.setLightState(options);
});
```
do you have an example for me

**Comment by atkinchris** [comment]
That's quite a strange way of setting a value - if you `log` the value of `options`, what does it give you?

Here's a snippet that's working with my bulbs for you to try.

```js
const { Client } = require('tplink-smarthome-api')

const client = new Client()
client.startDiscovery().on('bulb-new', async bulb => {
  const state = await bulb.lighting.getLightState()

  await bulb.lighting.setLightState({
    hue: 0,
    saturation: 0,
    color_temp: 3400,
    brightness: 50,
  })

  console.log('New bulb state set', state)
})
```

**Comment by rebeccasc** [comment]
I also have a problem with setting the lightstate. Tried the example above and it works with a defined value for the brightness (50) like above. But I want to use the output of a range slider by passing a variable. 

With this code (here I want to use `dimValue` as brightness value):

```
// on load
client.startDiscovery().on('device-new', (device) => {
  // dimmable layout
  if(device.deviceType == "bulb" && device.supportsBrightness){
    // add listener
    deviceSlider.oninput = function() {
      setLightStateOfDevice(device, this.value)
    };
  }
});

function setLightStateOfDevice(device, dimValue){
  device.lighting.setLightState({
    on_off: 1,
    brightness: dimValue
  })
}
```

I get this error:
```
C:\Users\r\kasa-control-center\node_modules\tplink-smarthome-api\lib\utils.js:39 
Uncaught (in promise) ResponseError: err_code not zero response: {"err_code":-10000,"err_msg":"invalid argument"} command: {"smartlife.iot.smartbulb.lightingservice":{"transition_light_state":{"ignore_default":1,"on_off":1,"brightness":"38"}}}
    at Object.processResponse (C:\Users\r\kasa-control-center\node_modules\tplink-smarthome-api\lib\utils.js:171:15)
    at Bulb.sendCommand (C:\Users\r\kasa-control-center\node_modules\tplink-smarthome-api\lib\device\index.js:271:33)
    at async Lighting.setLightState (C:\Users\r\kasa-control-center\node_modules\tplink-smarthome-api\lib\bulb\lighting.js:138:51)
```

Do I use it wrong or is this an issue with your code? 
Thanks in advance!

**Comment by plasticrake** [comment]
@rebeccasc you're setting it to a string instead of a number

**Comment by rebeccasc** [comment]
Oh.., you're right. Thanks!
