### ISSUE TITLE
API trying to look for Harmony Hub?

### ISSUE THREAD

**Issue by CoreISP** [plasticrake/tplink-smarthome-api#67]
Hi!

I have something strange as of today.
tplink-smarthome-api finds my WiFi plugs, but then also starts throwing errors:

[2/24/2019, 2:58:49 PM] [TplinkSmarthome.API] TCP Timeout
[2/24/2019, 2:58:49 PM] [TplinkSmarthome.API] [Ambilight] device.send() Error: TCP Timeout
[2/24/2019, 2:58:49 PM] [TplinkSmarthome] [Ambilight] 
[2/24/2019, 2:58:49 PM] [TplinkSmarthome] Error: TCP Timeout
    at Timeout.setTimeout (/homebridge/node_modules/tplink-smarthome-api/lib/client.js:228:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
errorhub { Error: connect ECONNREFUSED X.X.X.8:5222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: 'X.X.X.8',
  port: 5222 }

The X.X.X.8 turns out to be my Harmony Hub with XMPP enabled.
I'm not exactly sure why tplink-smarthome-api is trying to send requests to the Harmony Hub? 
It's not a tp-link device and it is messing up homekit causing an occassional crash, hehe. 

Interesting to add is that the plug it complains about "Ambilight" has a different IP.
It detects the two-plugs:
[2/24/2019, 2:54:35 PM] [TplinkSmarthome] New Device Online: [Switch1] plug [XXXXX] X.X.X.7 9999
[2/24/2019, 2:54:35 PM] [TplinkSmarthome] Adding: [Switch1] plug [XXXXXX]
[2/24/2019, 2:54:55 PM] [TplinkSmarthome] New Device Online: [Ambilight] plug [XXXXXXXX] X.X.X.54 9999
[2/24/2019, 2:54:55 PM] [TplinkSmarthome] Adding: [Ambilight] plug [XXXXXXX]
So one is on on .7 and one is on .54, both on port 9999. No idea why it's trying to interact with .8 which is the Harmony Hub. o0

Strange thing is I never had issues with this before, it just started happening today.
Already did a full reset of HomeBridge including getting rid of persist and cached devices, reloaded the whole thing and re-configured it: no go. 

Anyone have any idea why the tplink plugin is trying to do something with my Harmony Hub? It's kind of supposed to ignore that thing completely, no idea why it's trying to interact with it. 
Is there a way I can blacklist the IP specifically for the tp-link API? So that tplink-smarthome-api will not look/try to connect to the X.X.X.8 IP address? That should probably solve the problem and get HomeBridge back to stable.

**Comment by CoreISP** [comment]
Ok, reset the entirety of homebridge, killed all iCloud stuff (removed the entire home) and set the whole shebang back up. The error changed to:

[2/24/2019, 5:35:03 PM] [TplinkSmarthome.API] TCP Timeout
[2/24/2019, 5:35:03 PM] [TplinkSmarthome.API] [Ambilight] device.send() Error: TCP Timeout
[2/24/2019, 5:35:03 PM] [TplinkSmarthome] [Ambilight] 
[2/24/2019, 5:35:03 PM] [TplinkSmarthome] Error: TCP Timeout
    at Timeout.setTimeout (/homebridge/node_modules/tplink-smarthome-api/lib/client.js:228:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

No more extra notices of the Harmony Hub IP. Not sure why the Ambilight keeps failing to connect as it appears to be working just fine, but I guess for some reason it's finding it difficult to stay connected. But that's probably not an issue with the plugin.

Still not sure why on earth before the reset it kept spitting out nonsense about the Hub, but that seems to have fixed itself.

**Comment by plasticrake** [comment]
Closing due to inactivity. Please create a new issue if you're still having problems. Thanks!
