### ISSUE TITLE
"err_code":-3 on schedule.editrule for HS110 hardware version 2.0 (working on HS110 hardware version 1.0)

### ISSUE THREAD

**Issue by Ekhozie** [plasticrake/tplink-smarthome-api#89]
Hello,
First of all, great work on this API, it's very useful!
I have a problem with the method schedule.editRule on a new plug HS110 (hardware version 2.0, software version 1.5.3) whereas the same code is working on an old plug HS110 (hardware version 1.0, software version 1.0.10).
The error is 
```typescript
(node:7627) UnhandledPromiseRejectionWarning: ResponseError: err_code not zero response: {"err_code":-3,"err_msg":"invalid argument"} command: {"schedule":{"edit_rule":{"id":"1E8FE3EFDE18D7F9E025544BCC6E0F1F","sact":1,"name":"","enable":0,"emin":0,"etime_opt":-1,"smin":425,"stime_opt":0,"wday":[false,true,true,true,true,true,false],"repeat":true}}}
    at processResponse (/opt/vacation-mode/node_modules/tplink-smarthome-api/lib/device/index.js:84:11)
    at Plug.sendCommand (/opt/vacation-mode/node_modules/tplink-smarthome-api/lib/device/index.js:370:21)
```

API version is 2.0.0
Node.Js version is 12.14.1

Thanks for your support.

**Comment by plasticrake** [comment]
Yeah I noticed this too, it looks like the schedule format is different for those devices but I haven't had to time to figure out what is different yet. Would love it if someone could figure it out!
