### ISSUE TITLE
TCP Socket close with little Problem for us

### ISSUE THREAD

**Issue by arteck** [plasticrake/tplink-smarthome-api#96]
we use your lib as dependency on iobroker project.
and we have a exception problem 
```
2020-05-13 02:31:23.103 - error: hs100.0 (15163) uncaught exception: TCP Socket Closed. segment:0 hadError:false
2020-05-13 02:31:23.103 - error: hs100.0 (15163) Error: TCP Socket Closed. segment:0 hadError:false
at Socket. (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
at Object.onceWrapper (events.js:417:26)
at Socket.emit (events.js:310:20)
at TCP. (net.js:672:12)
2020-05-13 02:31:23.104 - debug: hs100.0 (15163) Error getDevice192.1.1.131
2020-05-13 02:31:23.106 - info: hs100.0 (15163) terminating

```

after a socket timeout .. any idea why the exception is unhandled

here the project
https://github.com/arteck/ioBroker.hs100

**Comment by plasticrake** [comment]
Is this still an issue on version 3?
